### PR TITLE
Remove stale comment about Apple ARM

### PR DESCRIPTION
**Pull request by fbricon**

### CODE REVIEW

**Review by rgrunber — APPROVED** [review]

**Comment by rgrunber** [comment]
Yup, https://github.com/redhat-developer/vscode-xml/issues/898 is fixed.

**Comment by fbricon** [comment]
@rgrunber https://github.com/redhat-developer/vscode-xml/pull/980/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R61 will soon need to go too right?

**Comment by rgrunber** [comment]
Was thinking that.. but no. On all Linux distros (except Alpine), we still require users to have libc because we're keeping it dynamically linked. It's just on Alpine that we won't. Is it worth adding a "except on Alpine x64" to that line ?

**Comment by fbricon** [comment]
yeah probably, for the sake of proper doco, as there's no other mention of alpine

**Pull request merged**
