### PR TITLE
Register _xml.applyCodeAction to fix bug with CodeAction apply

### PR DESCRIPTION
**Pull request by angelozerr**
This PR register a custom command "_xml.applyCodeAction" to apply CodeAction returned by the XML Language Server.

### CODE REVIEW

**Comment by fbricon** [comment]
I think the server should send commands instead of the new textedit (protocol 3.8.0), so more clients are supported. Else you need to customize each client with that specific applyCodeAction command.

**Comment by fbricon** [comment]
No. Server can only send CodeActions if the Client declares support for CodeAction literals, else it needs to fall back to returning command. That's why there are client capabilities

**Comment by angelozerr** [comment]
> No. Server can only send CodeActions if the Client declares support for CodeAction literals, else it needs to fall back to returning command. That's why there are client capabilities

So if I understand your comment:

 * lsp4xml should return list of CodeAction (like before) according the client capabilities
 * vscode-xml should configure literal support capabilities. 

In lsp4j, we have:

```
CodeActionCapabilities codeActionCapabilities = new CodeActionCapabilities();
			codeActionCapabilities.setCodeActionLiteralSupport(new CodeActionLiteralSupportCapabilities());
```
But in typescript, I have not found this defintion? Could you tell me how to do that please.

**Comment by fbricon** [comment]
No, the server must check if the client supports codeActions, by checking if capabilities.getTextDocument().getCodeAction().getCodeActionLiteralSupport() != null.
If codeActionLiteralSupport is supported, then return CodeActions. Else, return commands

**Comment by fbricon** [comment]
codeActionLiteralSupport.codeActionKind.valueSet should not be empty

**Comment by angelozerr** [comment]
> If codeActionLiteralSupport is supported, then return CodeActions. Else, return commands

Thanks for the feedback, done in https://github.com/angelozerr/lsp4xml/commit/89668441c8c6d8693744bb74ccfbfa7ae545a90d

> codeActionLiteralSupport.codeActionKind.valueSet should not be empty 

I have not implemented this test because LSP4e doesn't fill this codeActionLiteralSupport.codeActionKind.valueSet

**Comment by fbricon** [comment]
This PR is made obsolete by #37. Updating the vscode client makes vscode-xml support codeActionLiterals, so CodeActions are now supported OOTB.

**Pull request closed without merging**
