### PR TITLE
 Support for JRE & Oracle (javapath instead of bin)

### PR DESCRIPTION
**Pull request by angelozerr**
This PR is just to show you  how I have fixed the search of java home with my Windows context:

 * no JAVA_HOME path
 * "where java" returns "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe"
*  javapath is used insteaf of using bin

### CODE REVIEW

**Comment by GitMensch** [comment]
Coming here from #13 and wondering about the state of this PR - should the conflicts be fixed and the PR potentially be merged? Is that PR obsolete and should be closed instead?

**Comment by GitMensch** [comment]
Note: I'm also on a machine where `where java` works (returns `C:\ProgramData\Oracle\Java\javapath\java.exe` here) but the plugin needs a manual setup. Should it?

**Comment by fbricon** [comment]
This PR is stale. While the issue still exists, I think the best solution is to fix the detection mechanism upstream, or maybe, until this is fixed, reuse (and improve?) vscode-java's https://github.com/redhat-developer/vscode-java/blob/master/src/findJavaRuntimes.ts

**Comment by GitMensch** [comment]
> I think the best solution is to fix the detection mechanism upstream, or maybe, until this is fixed, reuse (and improve?) vscode-java's https://github.com/redhat-developer/vscode-java/blob/master/src/findJavaRuntimes.ts

That's very reasonable! Do you see anything that needs improvement there (then this likely should be fixed in that upstream repo first before pulling it into this repo). The best option here, if that would work which I don't know,, would be to move findJavaRuntimes.ts to a separate node module which can then be used in both (and other) projects.

**Comment by fbricon** [comment]
findJavaRuntime.ts doesn't support JRE detection at the moment, as vscode-java doesn't need it, so that definitely needs some improvements. Adding ./jenv/shim support would help bring feature parity with node-find-java-home (and adding sdkman support would be even better). @Eskibear any plans to publish it as a standalone npm module?

**Comment by Eskibear** [comment]
I was planning to contribute to `node-find-java-home`, adding a new API to return all possible Java runtimes. But that would possibly break backward compatibility of the library, see https://github.com/jsdevel/node-find-java-home/issues/28#issuecomment-718818582 I'll discuss with the owner later, see if we can make some progress.

A standalone npm module can also be an alternative.

**Comment by Eskibear** [comment]
I've published a npm package named [jdk-utils](https://www.npmjs.com/package/jdk-utils), which can list all installed Java runtimes, also coverring the Oracle Java SE 8 case.

image
image


Please give it a try and let me know if there's any case not coverred yet. See https://github.com/Eskibear/node-jdk-utils#findjavaruntime

**Comment by GitMensch** [comment]
So that's closed - how was it solved?

**Pull request closed without merging**
