### PR TITLE
Use JDK default GC

### PR DESCRIPTION
**Pull request by brunoborges**

### CODE REVIEW

**Comment by fbricon** [comment]
@brunoborges any specific reason for this change?

**Comment by brunoborges** [comment]
It won't work OOTB with a JDK that does not have G1GC, requiring user to tweak the config.

**Comment by fbricon** [comment]
I'm curious to know which JDKs don't have G1GC today. OracleJDK, OpenJDK, OpenJ9 have it, even with Java 8

**Comment by brunoborges** [comment]
I'm curious to understand then, why the core Java Language Support extension doesn't come with G1GC default setting. :-)

But to your point, a build of OpenJDK doesn't *have* to come with G1GC. Oracle's builds of OpenJDK don't come with Shenandoah for example.

**Comment by brunoborges** [comment]
@fbricon any other take on this?

**Comment by fbricon** [comment]
@rgrunber can you check this one please?

**Comment by rgrunber** [comment]
In redhat-developer/vscode-java#1262 we moved from G1 to ParalellGC to reduce the peak heap size. The goal was to not run out of heap in a container environment where that initial project import/build is what causes problems.

I could test this out and see if there's some downside, but I would assume vscode-xml isn't in the same position of needing such optimizations.

**Review by rgrunber — APPROVED** [review]
I'll merge this in, since as I mentioned, we're not in a position to need performance improvements on the LemMinx side, so we might as well ensure we support as many JVMs as we can with default settings.

**Pull request merged**
