### PR TITLE
Update vscode-languageclient to 7.0.0

### PR DESCRIPTION
**Pull request by datho7561**
This allows for `textDocument/linkedEditingRange` to be used.

Replaces #426

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
I think you can switch your draft PR in real PR.

**Comment by angelozerr** [comment]
I'm really annoying because this PR works good with master of LemMinx but with the Leinked Editing range PR https://github.com/eclipse/lemminx/pull/991 (even if linked editing range is disable) the server crashes (no completion, no validation, etc)

**Comment by datho7561** [comment]
I also get this. I'll play around with this a bit today to see if I can figure out what's going on.

**Review by angelozerr — APPROVED** [review]

**Comment by angelozerr** [comment]
This PR works great with LemMinx and with LSP4J 0.9 (master) and 0.11 but not for 0.12. As it's not a problem coming from this PR, I merge it. If 0.12 have a problem we can use 0.11 for linked editing range support.

Thanks @datho7561 !

**Pull request merged**
