### PR TITLE
Add 'xml.telemetry.enabled' settings

### PR DESCRIPTION
**Pull request by angelozerr**
Fix https://github.com/angelozerr/lsp4xml/issues/430

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by fbricon** [comment]
We're not gonna enable telemetry settings in vscode until we can actually collect the data

**Comment by angelozerr** [comment]
> We're not gonna enable telemetry settings in vscode until we can actually collect the data

You mean that vscode-xml must not provide `xml.telemetry.enabled `settings?  If it that it means that it's a more client capability?

**Comment by fbricon** [comment]
Please change the commit message as this doesn't "fix" the lsp4xml issue. Use "relates to" instead

**Comment by fbricon** [comment]
Actually we don't need this PR for now.

**Comment by angelozerr** [comment]
> Actually we don't need this PR for now.

I don't understand, how can we enable telemetry in this case since telemetry is disabled by default?

**Comment by fbricon** [comment]
we can still enable telemetry for testing purposes by adding xml.telemetry.enabled:true to the settings. It won't appear as a valid preference, but we power users will know ;-)

The preference will be exposed once vscode actually collect data

**Comment by angelozerr** [comment]
Ok thank's for the clarification @fbricon

**Pull request closed without merging**
