### PR TITLE
Support identation for XML contributed languages

### PR DESCRIPTION
**Pull request by angelozerr**
Support identation for XML contributed languages

### CODE REVIEW

**Comment by datho7561** [comment]
There is a bug with linked editing that makes proper tag indentation very annoying. For instance, if you have an `.svg` document:

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.w3.org/2000/svg https://www.w3.org/TR/2002/WD-SVG11-20020108/SVG.xsd">
  |
</svg>
```

If you add a tag `<aaa>` at the `|`, hit enter, then type in `</aaa>`, it will remove content from the opening tag when you type the last `>`.

This behaviour doesn't happen when you have tag auto closing, since the indentation isn't triggered if you have auto tag closing (eg. in xml and xsd files), but `.svg` files don't have auto indentation configured by default. However, if you disable auto tag closing, you can see the behaviour in XML and XSD files as well.

**Comment by datho7561** [comment]
broken-indentation

**Comment by angelozerr** [comment]
@datho7561 I created a PR to try to fix issue with linked editing range at https://github.com/eclipse/lemminx/pull/1457

But the bug that you found is not related to this vscode-xml PR indentation.

**Review by datho7561 — APPROVED** [review]
Looks good. Thanks, Angelo!

**Pull request merged**
