### PR TITLE
Add option to prevent self-closing from removing content

### LINKED ISSUE #440: Auto self-closing feature deletes content
Type `/` where the pipe is:

```xml
<foo |

  <baloney></baloney>

</foo>
```

Everything else is deleted:

SelfCloseDeletesContent

Expected result:

```xml
<foo />

  <baloney></baloney>

</foo>
```

### PR DESCRIPTION
**Pull request by datho7561**
Closes #440

Requires eclipse/lemminx#1009

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
Please add this settings in https://github.com/redhat-developer/vscode-xml/blob/master/docs/Preferences.md

**Review by rgrunber — COMMENTED** [review]
I don't think I'm seeing this behaviour, where the orphaned text and orphaned-element end tag are removed.

It does work in the cases you used in the tests and bug.

**Comment by datho7561** [comment]
It only happens when closing the root element; maybe that's why?

**Comment by rgrunber** [comment]
auto-close-on-orphaned-text

The docs seemed to imply that the orphaned content should also be removed, but I'm not seeing that. Let me know if I'm missing something in the explanation.

**Comment by datho7561** [comment]
> The docs seemed to imply that the orphaned content should also be removed, ...

The orphaned content is definitely not removed; I'll fix the documentation.

**Comment by datho7561** [comment]
Okay. I removed the nonsense I wrote and replaced it with actual documentation of the feature.

**Review by rgrunber — APPROVED** [review]
Thanks for fixing these up.

**Pull request merged**
