### PR TITLE
Upversion to 0.18.1

### PR DESCRIPTION
**Pull request by rgrunber**
Signed-off-by: Roland Grunberg <rgrunber@redhat.com>

### CODE REVIEW

**Comment by rgrunber** [comment]
We're currently at 0.18.1 in lemminx, so just matching it. Although very likely we'd go to 0.19.0 in the future, but depends on whichever features are added.

**Comment by angelozerr** [comment]
Could you squash your 2 commits in one please.

**Comment by rgrunber** [comment]
Whoops, sure.

**Review by angelozerr — APPROVED** [review]

**Comment by angelozerr** [comment]
Thanks @rgrunber !

**Pull request merged**
