### PR TITLE
Alpine support

### PR DESCRIPTION
**Pull request by cirolosapio**
- Fixes https://github.com/redhat-developer/vscode-xml/issues/986

### CODE REVIEW

**Comment by rgrunber** [comment]
Yup! this is almost exactly what I had locally. Still haven't fully tested though. I think https://github.com/redhat-developer/vscode-xml/pull/989/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L119 also needs to become `lemminx-{linux,alpine}` because the generated binary take the name of the `matrix.label`.

**Comment by cirolosapio** [comment]
reopened #991

**Comment by rgrunber** [comment]
I noticed the same issue.. for some reason when I tried doing a regular release, there was an issue uploading the artifact I think your approach of making the label, the "primary key" is the right one. I guess I must have only tested when alpine was on ubuntu-20.04 and linux was on ubuntu-22.04, and never tried having both on the same value.

**Comment by cirolosapio** [comment]
with this approach it compiles the right binary https://github.com/cirolosapio/vscode-xml/actions/runs/8808258955/job/24177003106

**Pull request closed without merging**
