### PR TITLE
Add support for `textDocument/linkedEditingRange`

### PR DESCRIPTION
**Pull request by angelozerr**
Add support for `textDocument/linkedEditingRange`

See https://github.com/eclipse/lemminx/issues/987

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
Here a demo:

MirrorCursorDemo

**Comment by fbricon** [comment]
unlike what Github says, there's a massive merge conflict with master

**Comment by fbricon** [comment]
oh now I see it in GH UI

**Comment by angelozerr** [comment]
Relaced with https://github.com/redhat-developer/vscode-xml/pull/432

**Comment by fbricon** [comment]
#432 does provide linked editing support

**Comment by angelozerr** [comment]
> #432 does provide linked editing support

Yes since this PR uses last vscode languageclient which supports linked editing range which is a part of LSP.

**Pull request closed without merging**
