### PR TITLE
Update Validation.md

### PR DESCRIPTION
**Pull request by GitMensch**
added rewrite sample - not ideal yet, but better than not mentioning it at all

### CODE REVIEW

**Review by datho7561 — CHANGES_REQUESTED** [review]
Thanks for your contribution! I think this is very helpful. I just have 2 small comments:
 * Could you please edit the commit message to describe what you are changing in the `Validation.md`? I think something like "Improve documentation for using catalogs" could be helpful.
 * See the comment below. If you don't think this change would be help, feel free to ignore the comment
Thanks again!

**Comment by GitMensch** [comment]
I agree completely on both of your points. But I can't edit the message without creating a new commit (I'm only on the end of a browser). Can I suggest you use the changes as template with a message `fixing #360` (so this gets closed on the way)?

**Comment by GitMensch** [comment]
For the change message:

> XML catalog with XSD -> added second example presenting the `rewriteURI` option

**Comment by angelozerr** [comment]
Close for https://github.com/redhat-developer/vscode-xml/pull/361

**Comment by angelozerr** [comment]
@GitMensch thanks for your contribution!

**Pull request closed without merging**
