### PR TITLE
Move to vscode-languageclient 8.0.1

### LINKED ISSUE #711: Move to vscode-languageclient 8.0.1
With vscode-languageclient 8.0.1, we will benefit with:

 * LSP 3.7 support
 * we could remove shouldLanguageServerExitOnShutdown

### PR DESCRIPTION
**Pull request by angelozerr**
Move to vscode-languageclient 8.0.1

Fixes #711

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
With this PR we need to test that:

 * XML features should work (completion, validation, hover, etc).
 * when we close the vscode, we must not have some zombie process (because I remove shouldLanguageServerExitOnShutdown)
 * when we change settings, we must test that it continues to work (refresh of settings should continue to work).

**Review by AlexXuChen — APPROVED** [review]
LGTM, XML features and settings are still working, and language server shuts down on close:
Peek 2022-05-19 10-02

**Comment by rgrunber** [comment]
Don't forget about the server-side property : https://github.com/eclipse/lemminx/blob/master/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/XMLLanguageServer.java#L230-L232

**Comment by angelozerr** [comment]
> Actually, I guess we can keep it for other clients ? It doesn't hurt to keep.

Indeed, it is rhe reason why I keep it.

> I can also confirm the behaviour is of shouldLanguageServerExitOnShutdown is enforced automatically in 8.0.1 without using the property. Note that we always would shut down the language server eventually (30s after close thanks to the parent process watcher, in the worst case), but this change preserves the immediate shutdown behaviour.

If I understand correctly, it works for you?

**Comment by rgrunber** [comment]
Yes, works for me :)

**Comment by angelozerr** [comment]
Nice, thanks for the fedback!

**Pull request merged**
